options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TAG: "manual"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/analytics-datapipeline-prod/risk-copilot-uat/server:${_TAG}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/analytics-datapipeline-prod/risk-copilot-uat/server:${_TAG}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'risk-copilot-app'
      - '--image=asia-south1-docker.pkg.dev/analytics-datapipeline-prod/risk-copilot-uat/server:${_TAG}'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--service-account=ltfs-customer-journey-instance@analytics-datapipeline-prod.iam.gserviceaccount.com'

images:
  - 'asia-south1-docker.pkg.dev/analytics-datapipeline-prod/risk-copilot-uat/server:${_TAG}'
